### PR TITLE
DM resolve IBP-4665 and IBP-4885

### PR DESCRIPTION
**Pull request by mchabito**

### CODE REVIEW

**Comment by darla-leafnode** [comment]
Hi @mchabito - why did we have to extract to a separate changeset file these scripts? we usually just maintain one changeset file per release and in this case we don't have an 18.3.1 release planned. 
We usually only have a _minor_ release (following the format <major/release version>.<sprint version>.<minor version> format) after bugfixing period or when releasing a hotfix.

**Comment by mchabito** [comment]
> 
> 
> Hi @mchabito - why did we have to extract to a separate changeset file these scripts? we usually just maintain one changeset file per release and in this case we don't have an 18.3.1 release planned.
> We usually only have a _minor_ release (following the format <major/release version>.. format) after bugfixing period or when releasing a hotfix.

Thanks @darla-leafnode, I have discarded 18_3_1.xml and appended its contents into 18_3_0.xml. 
I initially extracted into a separate file to avoid conflicts.

**Comment by mchabito** [comment]
For your review please @darla-leafnode , thanks!

**Comment by darla-leafnode** [comment]
Hi @mchabito - I copied you changesets into a new branch into an 18_4_1 crop changeset file.
Closing this PR in favor of that new branch [PR](https://github.com/IntegratedBreedingPlatform/Middleware/pull/1118)

**Pull request closed without merging**
